name: QMK userspace Build
on:
  workflow_dispatch:
  push:
    paths:
      - "keyboards/**"
      - "keymaps/*"
      - ".github/workflows/*"
      - "*.def"
      - "*.c"
      - "*.h"

jobs:
  list-user-keymaps:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "matrix=$(find keyboards -regex ".*keymaps" | sed "s|keyboards/\(.*\)/keymaps|\1|"| jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
      - run: echo $GITHUB_OUTPUT

  compile-userpace-keymaps:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    needs: list-user-keymaps
    strategy:
      fail-fast: false
      matrix:
        keyboards: ${{ fromJson(needs.list-user-keymaps.outputs.matrix) }}
    env:
      USERSPACE_PATH: users/${{ github.actor }}

    # by default, checks out to github.workspace
    # github.workspace will also be qmk_firmware root
    steps:
      - name: Checkout QMK
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          ref: master
          submodules: true

      - name: Checkout full userspace repository
        uses: actions/checkout@v4
        with:
          submodules: true  # <--- Wichtig!
          path: user_repo
          
      - name: Setup safe directory
        run: git config --global --add safe.directory '*'

      - name: Install rsync
        run: apt-get update; apt-get install -y rsync

      - name: Copy everything into QMK repo
        run: rsync -av user_repo/ .
        
      - name: QMK compile
        run: qmk compile -j 0 -kb ${{ matrix.keyboards }} -km ${{ github.actor }}

      - name: Generate unique artifact name
        id: artifact_name
        run: |
          timestamp=$(date +'%Y%m%d-%H%M%S')
          keyboard="${{ matrix.keyboards }}"
          echo "name=build_${keyboard}_${timestamp}" >> $GITHUB_OUTPUT

      - name: test
        run: echo keyboards/${{ matrix.keyboards }}/keymaps/${{ github.actor}}/keymap.c
        
      - name: Create json
        run: qmk c2json -o ${{ matrix.keyboards }}.json -km ${{ github.actor }} -kb ${{ matrix.keyboards }} keyboards/${{ matrix.keyboards }}/keymaps/${{ github.actor}}/keymap.c --no-cpp
        
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: ${{ steps.artifact_name.outputs.name }}
          path: |
            *.hex
            *.bin
            *.uf2
            *.json
            */*.json
              
